name: Regularly Check

on:
  schedule:
    - cron: "22 * * * *"
  workflow_dispatch:

jobs:
  commit-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Auto commit
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          if git commit --allow-empty -m "Regularly check"; then
            git push || echo "Push failed, skipping push."
          else
            echo "Commit failed, skipping push."
          fi
